# Dependabot will run on day 8 of each month at 03:35 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
    directories: "**/*"
